spring:
  application:
    name: demo
  rsocket:
    server:
      port: 8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: defaultDataSource
    url: jdbc:mysql://localhost:3306/shequ?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:  865130328

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  config-location:  classpath:mybatis-config.xml




